name: push_event
on: [push]
jobs:
  register_push_on_a_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -f nasapicoftheday.build.tar.gz
      - run: tar -czvf nasapicoftheday.build.tar.gz *.*
      - run: echo "Completed Task!  "
      - name: Upload output file
          uses: actions/upload-artifact@v2
          with:
            name: output-tar
            path: nasapicoftheday.build.tar.gz